Code - OSS (1.64.2, serv-9209.kl.dfki.de:64532, desktop)
Jupyter Extension Version: 2022.3.1000752054.
Python Extension Version: 2022.4.1.
Info 11:29:39: ZMQ install verified.
Error 11:29:39: Jupyter Extension (Error in Failed to update settings.json, method:fixSettingsFile): [EntryNotFound (FileSystemError): Unable to read file 'vscode-remote://serv-9209.kl.dfki.de:64532/root/.config/Code/User/settings.json' (Error: Unable to resolve nonexistent file 'vscode-remote://serv-9209.kl.dfki.de:64532/root/.config/Code/User/settings.json')
	at Function._handleError (/tmp/code-server-4.2.0-linux-amd64/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:93:83879)
	at Object.readFile (/tmp/code-server-4.2.0-linux-amd64/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:93:82793)
	at async m.readFile (/home/kadir/IML/Quantus/.code-server/extensions/ms-toolsai.jupyter-2022.3.1000752054/out/client/extension.js:2:118743)
	at async g.fixSettingsFile (/home/kadir/IML/Quantus/.code-server/extensions/ms-toolsai.jupyter-2022.3.1000752054/out/client/extension.js:2:4943)
	at async Promise.all (index 0)
	at async g.updateSettings (/home/kadir/IML/Quantus/.code-server/extensions/ms-toolsai.jupyter-2022.3.1000752054/out/client/extension.js:2:6705)] {
  code: 'FileNotFound'
}
Error 11:29:39: Jupyter Extension (Error in Failed to update settings.json, method:fixSettingsFile): [EntryNotFound (FileSystemError): Unable to read file 'vscode-remote://serv-9209.kl.dfki.de:64532/home/kadir/IML/Quantus/.vscode/settings.json' (Error: Unable to resolve nonexistent file 'vscode-remote://serv-9209.kl.dfki.de:64532/home/kadir/IML/Quantus/.vscode/settings.json')
	at Function._handleError (/tmp/code-server-4.2.0-linux-amd64/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:93:83879)
	at Object.readFile (/tmp/code-server-4.2.0-linux-amd64/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:93:82793)
	at async m.readFile (/home/kadir/IML/Quantus/.code-server/extensions/ms-toolsai.jupyter-2022.3.1000752054/out/client/extension.js:2:118743)
	at async g.fixSettingsFile (/home/kadir/IML/Quantus/.code-server/extensions/ms-toolsai.jupyter-2022.3.1000752054/out/client/extension.js:2:4943)
	at async Promise.all (index 1)
	at async g.updateSettings (/home/kadir/IML/Quantus/.code-server/extensions/ms-toolsai.jupyter-2022.3.1000752054/out/client/extension.js:2:6705)] {
  code: 'FileNotFound'
}
Info 11:29:40: Experiment status for python is {"enabled":true,"optInto":[],"optOutFrom":[]}
Info 11:29:40: Getting activation commands for /usr/bin/python3 are not cached. May take a while.
Info 11:29:40: Process Execution: > /usr/bin/python3 -m pip list
> /usr/bin/python3 -m pip list
Info 11:29:40: Process Execution: > /usr/bin/python3 -c "import pip"
> /usr/bin/python3 -c "import pip"
Info 11:29:55: Getting activation commands for /opt/conda/bin/python are not cached. May take a while.
Info 11:29:55: Activation Commands received source /opt/conda/bin/activate,conda activate base for shell bash
Info 11:29:56: Process Execution: > /opt/conda/bin/python -m pip list
> /opt/conda/bin/python -m pip list
